version: '3.8'

services:
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - graph_rag_resoluciones_graph_mongo_data:/data/db

  neo4j:
    image: neo4j:5.26.8
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/testpassword
    volumes:
      - graph_rag_resoluciones_neo4j_data:/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - graph_rag_resoluciones_qdrant_data:/qdrant/storage

volumes:
  graph_rag_resoluciones_graph_mongo_data:
    external: true
  graph_rag_resoluciones_neo4j_data:
    external: true
  graph_rag_resoluciones_qdrant_data:
    external: true
